name: Docker Runner

on:
  #schedule:
    # UTC (国内 UTC+8)
    #- cron: '1 */7 * * *'
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}
  DEVICE_NAME: ${{ secrets.DEVICE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Docker
      run : |
        sudo apt update -y && sudo apt install wget curl sudo -y
        curl -sSL https://get.daocloud.io/docker | sh

      
    - name: Run Docker Command and keep run
      run: |
        docker run -d --restart always --name tm traffmonetizer/cli start accept --token ${TOKEN} --device-name ${DEVICE_NAME}
        sudo bash bash.sh

